### ISSUE TITLE
How to turn location back on?

### ISSUE THREAD

**Issue by dbolser** [mrhaydendp/Fire-Tools#21]
I want to use this device as an in-car system, e.g. with maps.

How do I turn location services back on after debloat?

**Comment by dbolser** [comment]
WHen I looked there, a) the switch was already on, and b) it didn't allow
nova to see my location (for the weather widget)...

**Comment by mrhaydendp** [comment]
Since the fire tablet doesn't have a gps it needs wifi or Bluetooth scanning turned on. Those settings can be found in `Settings > Security & Privacy > Location-Based Services > Scanning`

**Comment by dbolser** [comment]
Oh wow, I thought it had GPS!

Is there any way I can 'give' it GPS via my phone?

**Comment by mrhaydendp** [comment]
Yes it's called Bluetooth gps pairing and you can get a dedicated Bluetooth gps or use your phone
