### ISSUE TITLE
Fire-Tool.ps1 Error in Powershell Windows 7

### ISSUE THREAD

**Issue by Wiki591** [mrhaydendp/Fire-Tools#23]
## Describe the bug:
The script stops with an error:
"Unerwartetes Token "{" im Ausdruck oder in der Anweisung.
Bei C:\Fire-Tools\Fire-Tools.ps1:202 Zeichen:24
+ $debloattool.Add_Click{ <<<< 
    + CategoryInfo          : ParserError: ({:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken"
## To Reproduce:
Starting the Fire-Tools.ps1 in Powershell under Windows 7

## Platform:
- Windows 7
- Just downloaded

## Device:
- Model Fire 10 2021
- Version  Fire OS 7.3.2.3

**Comment by mrhaydendp** [comment]
I haven't done any testing on Windows 7 as it's EOL, but we could try a few things. What version of Powershell do you have?

**Comment by mrhaydendp** [comment]
This page on the Microsoft docs shows how to list the current version of Powershell and how to update it:
https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7.2

**Comment by Wiki591** [comment]
Hi,

Thanks for your fast reaction and the link. I don't know why I didn't search by myself.

My Powershell tells me the PSVersion 2.0. Seems it is pretty old following the version history on Microsoft's pages.

I will update, try again and I will report again.

**Comment by Wiki591** [comment]
Hi again,

tokk a little bit but I ran through the updates for the powershell step by step to give you the opportunity for documenting prerequisites for the scripts. And my old black brick called Lenovo X201 is a little bit kind of slow........

PS Version 2.0: doesn't work
PS Version 3.0: doesn't work, too. Longer but almost similar error message compaired to 2.0
PS Version 4.0 and 5.0: Unable to test, downloads no longer available at Microsoft
PS Version 5.1: works.

Thanks again for your help, Wiki
