### ISSUE TITLE
Failed to disable several packages + ads coming back

### ISSUE THREAD

**Issue by LeoCal** [mrhaydendp/Fire-Tools#27]
## Describe the bug:
On my Fire HD 10, latest OS version (7.3.2.6), I encounter 2 issues:
1. When trying to debloat, I get a "success", but I also get a list of packages that the tool fails to disable:
```
Failed to Disable: com.amazon.alexa.multimodal.gemini
Failed to Disable: com.amazon.tcomm.client
Failed to Disable: com.amazon.kindle.otter.oobe
Failed to Disable: com.fireos.usagestats.proxy
Failed to Disable: com.amazon.sync.service
Failed to Disable: com.amazon.client.metrics
Failed to Disable: com.amazon.tv.launcher
Failed to Disable: com.amazon.minerva.client.api
Failed to Disable: com.amazon.tcomm
Failed to Disable: com.fireos.arcus.proxy
Failed to Disable: com.amazon.device.sync
Failed to Disable: com.amazon.sync.service
Failed to Disable: com.amazon.csapp
Failed to Disable: com.amazon.diode
Failed to Disable: com.amazon.device.sync.sdk.internal
Failed to Disable: com.amazon.identity.auth.device.authorization
Failed to Disable: com.amazon.legalsettings
Failed to Disable: com.amazon.platform
Failed to Disable: com.amazon.device.messaging
Failed to Disable: com.amazon.device.metrics
Failed to Disable: com.amazon.securitysyncclient
Failed to Disable: com.amazon.pm
Failed to Disable: com.amazon.kindle.kso
Failed to Disable: com.amazon.whisperlink.core.android
```

2. Despite the failures, it seems the device is pretty much debloated; however, after a few hours, ads announcements are coming back on the lock screen of the device. 

## To Reproduce:

- Connect the tablet to my Mac and run the tool
- Check the tool logs (see them copy-pasted in the previous section) and noticed how several packages fail to be disabled
- Also, wait for some hours and notice how ads are back

## Expected behavior:
Device should be successfully debloated with no error logs and ads should not come back.

## Platform:
- OS: MacOS 13.0.1
- Latest Version of Script? Yes, 22.10.1

## Device:
- Model Fire HD 10 (11th gen)
- Version: Fire OS 7.3.2.6

**Comment by mrhaydendp** [comment]
Fire OS 7.3.2.2 added a device administrator application that protects certain apps from being disabled, although most get disabled. As for the ads coming back, did you log in to your Amazon account on the tablet?

**Comment by LeoCal** [comment]
Yes, in fact that’s quite possible.

So I guess ads are getting pushed back from Amazon account?

**Comment by mrhaydendp** [comment]
Yes, Amazon checks if you purchased the ad-free version of the tablet using your account. You can deregister (sign out) your device by going to Settings > My Account > Deregister. After de-registering I recommend re-running the tool then rebooting the tablet.

**Comment by LeoCal** [comment]
Ok, thanks for the info!
