### ISSUE TITLE
Enable calendar service for third part calendar apps

### ISSUE THREAD

**Issue by Delfx** [mrhaydendp/Fire-Tools#28]
## Describe the bug:

Everything is working perfect on Mac. But I have question how to enable and what service to enable for Google calendar to work?

## Platform:
- macos
- Latest Version of Script? Yes

## Device:
- Model fire 10 
- Version  Fire OS 7.3.2.6

**Comment by mrhaydendp** [comment]
I believe only Calendar Storage is needed, you can enable it by running this command in Terminal:
```
adb shell pm enable com.android.providers.calendar
```

**Comment by Delfx** [comment]
Thanks, that helps :)
