### ISSUE TITLE
Cannot use program. Says ADB isn't installed.

### ISSUE THREAD

**Issue by SparklingWaterBurns** [mrhaydendp/Fire-Tools#31]
## Describe the bug:
I am attempting to make use of an old Fire tablet from 2017, but i simply can't use the program because it thinks ADB isn't installed. (platform-tools folder is in my home folder. Fire-Tools is also in there.)

Developer Mode and USB debugging is turned on on my fire.

## Expected behavior:
To be able to use the program and have it detect ADB installed.

## Platform:
- Linux, Latest script

## Device:
- Model: Fire HD 10 (7th Gen)
- Version: Fire OS 5.7.0.0

## Additional context:
![Screenshot 2023-01-19 6 31 28 PM](https://user-images.githubusercontent.com/110859540/213592814-5fc73922-57c9-41c6-b369-66d3e329d0c2.png)

ADB works with my fire tablet.

**Comment by mrhaydendp** [comment]
The tool expects adb to be installed through your distros package manager (apt, pacman, dnf, etc). I see you're running Debian through Chrome OS's Linux container, so you would use apt.
```
sudo apt install adb
```

**Comment by SparklingWaterBurns** [comment]
It works, but now i get this error instead:
`./ui.sh: 32: zenity: not found`
what is it trying to find?

**Comment by mrhaydendp** [comment]
Zenity is the GUI tool needed for Fire-Tools, it can be installed using:

``` bash
sudo apt install zenity
```

I'll update the setup instructions to include Chrome OS so it's not as confusing.

**Comment by SparklingWaterBurns** [comment]
Got it fixed but it's not recognizing my fire or my phone anymore.
USB Debugging is turned on in Developer Settings.

**Comment by mrhaydendp** [comment]
I've had that happen a couple times to fix it, on your Fire Tablet go to Device Options > Developer Options > Default USB Configuration and set it to File Transfer

**Comment by SparklingWaterBurns** [comment]
I tried it and it still won't work. the Fire's cable is good and the Chromebook detects it but adb won't.

**Comment by SparklingWaterBurns** [comment]
I have a USB converter dongle laying around. 
The USB-C plug fits into my phone only (fire uses a different type.) I can plug my fire's cable into the converter and then plug it into my Chromebook and that's the only way.

**Comment by SparklingWaterBurns** [comment]
After a reboot of ChromeOS and clearing USB debugging authorizations, It recognized the device!!

**Comment by SparklingWaterBurns** [comment]
FIre Tools says device is unknown/unsupported??

**Comment by SparklingWaterBurns** [comment]
could enabling/disabling widgets be a feature? just tried it with a command and it worked:
`adb shell appwidget grantbind --package com.teslacoilsw.launcher --user 0`

**Comment by SparklingWaterBurns** [comment]
![Screenshot 2023-01-21 11 46 42 PM](https://user-images.githubusercontent.com/110859540/213902546-0be04527-d4d0-4fba-b609-eb7dc5f781ec.png)
I found a bug. Tried to switch the launcher but it tried installing an already installed app.

**Comment by mrhaydendp** [comment]
I'm working on a way to automatically enable widgets for whatever launcher you choose, even .apks.

**Comment by mrhaydendp** [comment]
That error is my bad I forgot to add the Nova and Lawnchair .apks for the latest release but I'll have an updated version by tomorrow.

**Comment by SparklingWaterBurns** [comment]
Apparently debloat worked with one app but Fire OS fixed it and now it stopped...
All i'm getting are java.lang.IllegalArgumentExceptions when it tries to run.
![Screenshot 2023-01-23 8 56 43 PM](https://user-images.githubusercontent.com/110859540/214203563-54e25dbc-9790-4256-bfc5-ad7a1ee2e574.png)

**Comment by mrhaydendp** [comment]
Looks like adb is having problems connecting because those packages are present on all fire tablets & the tool will skip to the next package if it can't disable the one that it's working on.
