### ISSUE TITLE
Fire HD 8 2018 8th gen: can't install GPlay because of INSTALL_FAILED_OLDER_SDK

### ISSUE THREAD

**Issue by PieBru** [mrhaydendp/Fire-Tools#33]
Hi, I'm on Arch Linux, adb and FT are working and debloat cleaned a lot my good old Fire HD 8 2018.
GPlay seems installed OK, but I'm not able to login to gplay because the other apk(m) didn't install, giving `INSTALL_FAILED_OLDER_SDK` error.

Here is the (almost) full console log:
```
./ui.sh
Device Connected
Archive:  ./Gapps/Google Play Services 22.48.55.apkm
  inflating: ./Split/META-INF/MANIFEST.MF  
...
 extracting: ./Split/APKM_installer.url  
adb: failed to finalize session
Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1884589577.tmp/base.apk (at Binary XML file line #11): Requires newer sdk version #28 (current version is #25)]
Archive:  ./Gapps/Google Play Store 33.6.13-21.apkm
  inflating: ./Split/META-INF/MANIFEST.MF  
...
 extracting: ./Split/APKM_installer.url  
Success
Performing Streamed Install
adb: failed to install ./Gapps/Google Services Framework 10-6494331.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl725527478.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #25)]
Performing Streamed Install
adb: failed to install ./Gapps/Google Services Framework 9-6957767.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1746226359.tmp/base.apk (at Binary XML file line #0): Requires newer sdk version #28 (current version is #25)]
Archive:  ./Gapps/Google Play Store 33.6.13-21.apkm
  inflating: ./Split/META-INF/MANIFEST.MF  
...
 extracting: ./Split/APKM_installer.url  
Success
Successfully Installed Google Apps
Device Connected
```

Can I try something else?

Thank you,
Piero

**Comment by mrhaydendp** [comment]
The issue is your Fire tablet is running Android 7.1 but this tool is made with android 8+ in mind

**Comment by mrhaydendp** [comment]
You can either update your tablet or get apk(m)s that are compatible and put them in the `Batch` folder.

Here's a list of compatible apk(m)s you'll need:
- https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-23-03-13-release/google-play-services-23-03-13-040400-503260631-2-android-apk-download/
- https://www.apkmirror.com/apk/google-inc/google-services-framework/google-services-framework-7-1-1-release/google-services-framework-7-1-1-2-android-apk-download/

**Comment by PieBru** [comment]
Thank you, it worked well.
Sorry for my delay.
Piero
