### ISSUE TITLE
Auto Updater does not work with minor versions

### ISSUE THREAD

**Issue by OttersMeep** [mrhaydendp/Fire-Tools#45]
## Steps to Reproduce:

- Install 24.04 on Linux
- Run app
- Click the update button in the top left
<img width="1379" alt="SCR-20240428-nfcx" src="https://github.com/mrhaydendp/Fire-Tools/assets/107761109/d2dda226-b68d-4718-a0cd-e09941fb36ee"> (MacOS)

## Expected Behavior:
Converts "24.04.1" to a float (which is completely impossible)

## Platform:
- Linux/MacOS (reproduced on both)

## Additional Context (Optional):
Floats can't store double decimal numbers like "24.04.1", those aren't "real" numbers

No idea how to solve this, since looking over your code, it should work fine

EDIT: looked over the recent additions and saw that the update issue was fixed. However, anyone using the updater will encounter issues unless they download the newest raw file from Github directly

**Comment by mrhaydendp** [comment]
Yeah I realized that soon after I made the fix but haven't had time to update the release with the patched version. I'll have some time tonight to update it. Thank you for looking out!

**Comment by OttersMeep** [comment]
Maybe add a big banner in the README saying smth along the lines of "If you came here because of updater issues, they have been resolved; download latest version"
