### ISSUE TITLE
Does not work!

### ISSUE THREAD

**Issue by sYnapZiX** [mrhaydendp/Fire-Tools#50]
## Describe the Bug:
The app/script does flatout not work.

## Steps to Reproduce:
Launch the script (python3 main.py)
Watch the error

## Error Message:
Traceback (most recent call last):
  File "G:\Downloads\Fire-Tools\main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

## Expected Behavior:
A working app/script?

## Platform:
- Windows 11 x64
- Python 3.12
- Latest Version of Script, Yes downloaded 5 min's ago

**Comment by mrhaydendp** [comment]
Did you install the necessary Python dependencies? You can install the requests package by running:
``` PowerShell
python.exe -m pip install reqests
```

**Comment by janstadt** [comment]
I get this even after installing via requirements.txt

**Comment by janstadt** [comment]
I read through the readme and installing `pip3 install customtkinter requests` and then running as sudo got me all up and going.

**Comment by mrhaydendp** [comment]
> I read through the readme and installing `pip3 install customtkinter requests` and then running as sudo got me all up and going.

Yeah on Linux it's pip3 for Python3 but on Windows pip works
