### ISSUE TITLE
Script runs fine, no effect on tablet

### ISSUE THREAD

**Issue by CRUMPUTER** [mrhaydendp/Fire-Tools#53]
## Describe the Bug:
Script states that bloat is removed and google apps are installed, but nothing changes on the tablet itself.

## Steps to Reproduce:
I followed the setup instructions to a T and ran the python script. The Fire Tools window was all white (no visible text/buttons), but I used a screen shot to move the cursor to the desired locations (debloat, install google) and when I clicked each, the script itself ran and stated success. However, nothing changed on the tablet.

My computer is a 4 year-old MacBook. The tablet is a 7th gen Amazon Fire. 

The setup instructions tell me to "Scroll down to "Default USB configuration", tap it, then select "File Transfer"", but on my tablet it has MTP or PTP. I've tried both with no success.

## Platform:
macOS Sonoma 14.4.1

## Device:
Fire HD 10 (7th Gen)

## Additional Context (Optional):
N/A

**Comment by mrhaydendp** [comment]
Is your device detected? It should say the model in the Terminal and titlebar of the application. If not, does your cable support file transfer? You can also type this command into a new Terminal to see if your device is detected:

``` shell
adb devices
```

**Comment by CRUMPUTER** [comment]
The command does return my device. However, when I run the fire tools script, the “Device” line is blank, though the “Software” line does show “Fire OS 5.7.1.0”. 

I’ve tried four different cables.

**Comment by mrhaydendp** [comment]
It looks like your device is running Android 5.1. My tool only supports Android 8+ since I don't have any devices older than 7. I'm away and don't have a computer with me but I can help give some commands to make Debloat.txt work on your device. Also, can you send a screenshot of Fire Tools on your system?

**Comment by mrhaydendp** [comment]
Were any of the apps in Debloat.txt able to be disabled? Can you send the Terminal log?

**Comment by CRUMPUTER** [comment]
You’re a saint. 

I’ll get you the terminal log and screenshot in the morning (mine, anyway). 

My primary goal is to install the Google play store, versus debloating. Any reason I can’t connect to WiFi, update the FireOS, then run Fire Tools?

**Comment by mrhaydendp** [comment]
Connecting to Wi-Fi, at least on newer versions, will force you to log into an Amazon account. Some people have also reported not being able to remove lockscreen ads after logging in, even after logging out.

**Comment by mrhaydendp** [comment]
Since you're running a lower Android version, you'll need different Google apps than are included. I can make a list of .APK files that you can download directly on the tablet or install with the Batch Installer function of the tool.

- Google Play Services
- Google Play Store
- Google Account Manager
- Google Services Framework

**Comment by mrhaydendp** [comment]
Were you able to get the Play Store installed?

**Comment by obrien-james** [comment]
Hi I am in the same situation. I downloaded the apks from the links you provided added them to the batch folder and batch installed them. 

It says they installed successfully, but I dont see them on the fire tablet:

<img width="909" alt="image" src="https://github.com/user-attachments/assets/6a16a63b-1d21-4920-9813-64eef30e24ff">

Would also want to change the launcher etc... 

The debloat reports its successful, but I'm not sure how to check this
