### ISSUE TITLE
Run the tool but no effect

### ISSUE THREAD

**Issue by obrien-james** [mrhaydendp/Fire-Tools#60]
Hi I am in the same situation as [this](https://github.com/mrhaydendp/Fire-Tools/issues/53). 

Fire tab 7th gen - Fire os 5.7.0

I downloaded the apks from the links you provided added them to the batch folder and batch installed them. 

It says they installed successfully, but I dont see them on the fire tablet:

<img width="909" alt="image" src="https://github.com/user-attachments/assets/6a16a63b-1d21-4920-9813-64eef30e24ff">

Would also want to change the launcher etc... 

The debloat reports its successful, but I'm not sure how to check this

_Originally posted by @obrien-james in https://github.com/mrhaydendp/Fire-Tools/issues/53#issuecomment-2446178370_

**Comment by mrhaydendp** [comment]
The problem is this tool was made for Android 8.0+ in mind but Fire OS 5.7 is Android 5.1, so some commands don't work properly or the same. I can give you some commands to manually run when I get home to get the debloat list working and install Google services if you'd like.

**Comment by obrien-james** [comment]
That would be very helpful mate.

thanks

**Comment by mrhaydendp** [comment]
You should be able to open the debloat.sh script in Fire-Tools/Scripts/Posix and replace:
``` bash
adb shell pm disable-user "$app" >/dev/null 2>&1 && adb shell pm clear "$app" > /dev/null;;
```
with
``` bash
adb shell pm uninstall --user 0 "$app" >/dev/null 2>&1 && adb shell pm clear "$app" > /dev/null;;
```

**Comment by obrien-james** [comment]
Thanks I will give I a go

**Comment by mrhaydendp** [comment]
The batch installer should work regardless of the Android version. It could be the APKs that I recommended, here are the recommended ones for the 7th gen Fire tablets according to [Android Police](https://www.androidpolice.com/install-play-store-amazon-fire-tablet/):
- [Google Account Manager](https://www.apkmirror.com/apk/google-inc/google-account-manager/google-account-manager-5-1-1743759-release/)
- [Google Services Framework](https://www.apkmirror.com/apk/google-inc/google-services-framework/google-services-framework-5-1-1743759-release/google-services-framework-5-1-1743759-android-apk-download/)
- [Google Play Services](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-24-05-15-release/google-play-services-24-05-15-020300-607433892-android-apk-download/)
- [Google Play Store](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-43-3-32-release/google-play-store-43-3-32-31-0-pr-689609405-2-android-apk-download/)

**Comment by mrhaydendp** [comment]
You can also install them directly from the tablet by transfering the APKs to a folder on the device and opening them with the Files app. Could you also run `adb shell pm list packages -3` and share the output so I can see if any of the apps actually installed or just showed a false success message?
