### ISSUE TITLE
How i can change launcher with brevent adb

### ISSUE THREAD

**Issue by GithubUser559** [mrhaydendp/Fire-Tools#62]
With brevent you can run adb shell commands without computer.  My tablet is amazon fire max 11.  What code should I put to change the launcher  to nova launcher  (please test  in a real fire tablet)

**Comment by mrhaydendp** [comment]
Newer fire tablets can't disable the fire launcher so you will have to install launcher hijack and your preferred launcher. Once installed you can select your launcher in the app.

**Comment by GithubUser559** [comment]
@mrhaydendp I can disable ads by adb shell? What adb shell comando use fire toolbox to disable ads

**Comment by mrhaydendp** [comment]
The debloat function does all of these

``` shell
# Disable Telemetry & Reset Advertising ID"
adb shell settings put secure limit_ad_tracking 1
adb shell settings put secure usage_metrics_marketing_enabled 0
adb shell settings put secure USAGE_METRICS_UPLOAD_ENABLED 0
# Disable Location Services
adb shell settings put secure location_providers_allowed -network
# Disable Lockscreen Ads
adb shell settings put global LOCKSCREEN_AD_ENABLED 0
# Disable Search on Lockscreen
adb shell settings put secure search_on_lockscreen_settings 0
# Set Animation Scale to 0.5x
adb shell settings put global window_animation_scale 0.50
adb shell settings put global transition_animation_scale 0.50
adb shell settings put global animator_duration_scale 0.50
```

**Comment by GithubUser559** [comment]
@mrhaydendp This is my last question, if I run the announcements command from brevent, will it work as if I had used fire toolbox?

**Comment by GithubUser559** [comment]
I would like a non-computer version of Fire Toolbox that would work with Shizuku. Shizuku is an app that allows you to run ADB shell commands without a computer just like Brevent. An external app can enter commands into Shizuku thanks to an option. That's why I think a non-computer lite version of Fire Toolbox would be possible.

**Comment by mrhaydendp** [comment]
> @mrhaydendp This is my last question, if I run the remove  ads command from brevent, will it work as if I had used fire toolbox? 

Yes this will work just like Fire Tools minus disabling packages.

**Comment by mrhaydendp** [comment]
> I would like a non-computer version of Fire Toolbox that would work with Shizuku. Shizuku is an app that allows you to run ADB shell commands without a computer just like Brevent. An external app can enter commands into Shizuku thanks to an option. That's why I think a non-computer lite version of Fire Toolbox would be possible. 

Thank you for the suggestion! That's not really in the scope of this project but it is something I have thought about.
